// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mNHCD9oo5MpprbrWsDKi7dRngXRK6Ds',
    appId: '1:482821091519:web:f2fb3a44c109dbae54160a',
    messagingSenderId: '482821091519',
    projectId: 'three-d-track-app',
    authDomain: 'three-d-track-app.firebaseapp.com',
    storageBucket: 'three-d-track-app.firebasestorage.app',
    measurementId: 'G-QKF3W8ET2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_CRnGTQDI1gZ3UDYKemTW3Sfb-UoyCE',
    appId: '1:482821091519:android:a80c7975a0b73f3554160a',
    messagingSenderId: '482821091519',
    projectId: 'three-d-track-app',
    storageBucket: 'three-d-track-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eyvmcZikD6lru5Qyhm7yT-CquM0ql8c',
    appId: '1:482821091519:ios:7b73ee78db7cb10254160a',
    messagingSenderId: '482821091519',
    projectId: 'three-d-track-app',
    storageBucket: 'three-d-track-app.firebasestorage.app',
    iosBundleId: 'com.threeddaic.three3dtrack.three3dTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6eyvmcZikD6lru5Qyhm7yT-CquM0ql8c',
    appId: '1:482821091519:ios:7b73ee78db7cb10254160a',
    messagingSenderId: '482821091519',
    projectId: 'three-d-track-app',
    storageBucket: 'three-d-track-app.firebasestorage.app',
    iosBundleId: 'com.threeddaic.three3dtrack.three3dTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5mNHCD9oo5MpprbrWsDKi7dRngXRK6Ds',
    appId: '1:482821091519:web:233eda5ac415934754160a',
    messagingSenderId: '482821091519',
    projectId: 'three-d-track-app',
    authDomain: 'three-d-track-app.firebaseapp.com',
    storageBucket: 'three-d-track-app.firebasestorage.app',
    measurementId: 'G-FM4HZ51BFQ',
  );
}
